// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pogomq struct {
	AutoComplete     bool
	Body             []byte
	Completed        pgtype.Timestamptz
	DeliveryCount    int32
	ID               string
	MaxDeliveryCount int32
	Scheduled        pgtype.Timestamptz
	Topic            string
	TtlSeconds       pgtype.Int8
	Ttl              pgtype.Timestamptz
}
