// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeMessage = `-- name: CompleteMessage :exec
UPDATE
  pogomq
SET
  completed = (NOW() AT TIME ZONE 'UTC')
WHERE
  id = $1
  AND completed IS NULL
`

func (q *Queries) CompleteMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeMessage, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM
  pogomq
WHERE
  id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

type EnqueueMessagesParams struct {
	AutoComplete     bool
	Body             []byte
	ID               string
	MaxDeliveryCount int32
	Scheduled        pgtype.Timestamptz
	Topic            string
}

const failMessage = `-- name: FailMessage :exec
UPDATE
  pogomq
SET
  completed = NULL,
  scheduled = $1
WHERE
  id = $2
  AND delivery_count < max_delivery_count
`

type FailMessageParams struct {
	Scheduled pgtype.Timestamptz
	ID        string
}

func (q *Queries) FailMessage(ctx context.Context, arg FailMessageParams) error {
	_, err := q.db.Exec(ctx, failMessage, arg.Scheduled, arg.ID)
	return err
}

const messageCounts = `-- name: MessageCounts :one
WITH message_counts AS (
  SELECT
    CASE
      WHEN completed IS NULL AND delivery_count < max_delivery_count AND scheduled <= (NOW() AT TIME ZONE 'UTC') THEN 'active'
      WHEN completed IS NULL AND delivery_count >= max_delivery_count THEN 'failed'
      WHEN completed IS NULL AND scheduled > (NOW() AT TIME ZONE 'UTC') THEN 'scheduled'
      WHEN completed IS NOT NULL THEN 'completed'
      ELSE 'unknown'
    END AS message_state
  FROM
    pogomq
  WHERE
    topic = $1
)
SELECT
  COALESCE(SUM(CASE WHEN message_state = 'active' THEN 1 ELSE 0 END), 0) :: INT AS active_count,
  COALESCE(SUM(CASE WHEN message_state = 'failed' THEN 1 ELSE 0 END), 0) :: INT AS failed_count,
  COALESCE(SUM(CASE WHEN message_state = 'scheduled' THEN 1 ELSE 0 END), 0) :: INT AS scheduled_count,
  COALESCE(SUM(CASE WHEN message_state = 'completed' THEN 1 ELSE 0 END), 0) :: INT AS completed_count
FROM
  message_counts
`

type MessageCountsRow struct {
	ActiveCount    int32
	FailedCount    int32
	ScheduledCount int32
	CompletedCount int32
}

func (q *Queries) MessageCounts(ctx context.Context, topic string) (MessageCountsRow, error) {
	row := q.db.QueryRow(ctx, messageCounts, topic)
	var i MessageCountsRow
	err := row.Scan(
		&i.ActiveCount,
		&i.FailedCount,
		&i.ScheduledCount,
		&i.CompletedCount,
	)
	return i, err
}

const purgeMessages = `-- name: PurgeMessages :exec
DELETE FROM
  pogomq
WHERE
  completed < $1
  AND topic = $2
`

type PurgeMessagesParams struct {
	Before pgtype.Timestamptz
	Topic  string
}

func (q *Queries) PurgeMessages(ctx context.Context, arg PurgeMessagesParams) error {
	_, err := q.db.Exec(ctx, purgeMessages, arg.Before, arg.Topic)
	return err
}

const rescheduleMessages = `-- name: RescheduleMessages :exec
UPDATE
  pogomq
SET
  scheduled = (NOW() AT TIME ZONE 'UTC') 
WHERE
  topic = $1
  AND completed IS NULL
  AND delivery_count < max_delivery_count
  AND scheduled < (NOW() AT TIME ZONE 'UTC')
`

func (q *Queries) RescheduleMessages(ctx context.Context, topic string) error {
	_, err := q.db.Exec(ctx, rescheduleMessages, topic)
	return err
}

const resetFailedMessages = `-- name: ResetFailedMessages :exec
UPDATE
  pogomq
SET
  completed = NULL,
  scheduled = (NOW() AT TIME ZONE 'UTC'),
  delivery_count = 0
WHERE
  topic = $1
  AND completed IS NOT NULL
`

func (q *Queries) ResetFailedMessages(ctx context.Context, topic string) error {
	_, err := q.db.Exec(ctx, resetFailedMessages, topic)
	return err
}
